@baseUrl = http://localhost:3000

GET {{baseUrl}}/messages

###
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "content": "Operation successful again!!"
}

###
GET {{baseUrl}}/messages/238